title: "Portfolio"
description: "My Projects"
theme: minima
url: "https://mahdishahsavar.github.io"
baseurl: "" # For user or org site
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
  # ...other supported plugins
